export enum GroupEventLog {
  // GROUP
  GROUP_UPDATED = 'GROUP_UPDATED',

  // SETTING
  GROUP_SETTING_CHANGED = 'GROUP_SETTING_CHANGED',

  // REQUEST
  JOIN_REQUEST_APPROVED = 'JOIN_REQUEST_APPROVED',
  JOIN_REQUEST_REJECTED = 'JOIN_REQUEST_REJECTED',

  // MEMBER
  MEMBER_JOINED = 'MEMBER_JOINED',
  MEMBER_LEFT = 'MEMBER_LEFT',
  MEMBER_REMOVED = 'MEMBER_REMOVED',
  MEMBER_BANNED = 'MEMBER_BANNED',
  MEMBER_UNBANNED = 'MEMBER_UNBANNED',

  // post
  POST_APPROVED = 'POST_APPROVED',
  POST_REJECTED = 'POST_REJECTED',

  // ROLE & PERMISSION
  MEMBER_ROLE_CHANGED = 'MEMBER_ROLE_CHANGED',
  MEMBER_PERMISSION_CHANGED = 'MEMBER_PERMISSION_CHANGED',
}
