name: Native Preview Updates

on:
  push:
    branches:
      - develop
    paths:
      - apps/native/app/**
      - apps/native/components/**
      - apps/native/constants/**
      - apps/native/hooks/**
      - apps/native/lib/**
      - apps/native/providers/**
      - apps/native/utils/**
      - packages/shared/src/**
      - packages/ui/src/**
      - !**/*.md
  workflow_dispatch:

jobs:
  publish_preview_update:
    name: Publish preview update
    environment: preview
    type: update
    params:
      branch: preview
